services:
  - type: web
    name: spotifywrapped
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn SpotifyWrapped.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: spotifywrapped-db
          property: connectionString

databases:
  - name: spotifywrapped-db
    databaseName: spotifywrapped
    user: spotifywrapped