# Generated by Django 5.1.2 on 2024-11-04 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyWrapped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_artist", models.CharField(max_length=255)),
                ("top_track", models.CharField(max_length=255)),
                ("top_genre", models.CharField(max_length=255)),
                ("playlist_url", models.URLField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "top_artist_image",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "top_track_image",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "top_track_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
