# Generated by Django 5.1.2 on 2024-11-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotifywrapped",
            options={},
        ),
        migrations.RemoveField(
            model_name="spotifywrapped",
            name="top_artist_image",
        ),
        migrations.RemoveField(
            model_name="spotifywrapped",
            name="top_track_image",
        ),
        migrations.RemoveField(
            model_name="spotifywrapped",
            name="user",
        ),
        migrations.AddField(
            model_name="spotifywrapped",
            name="spotify_display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spotifywrapped",
            name="spotify_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="spotifywrapped",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
