# Generated by Django 5.1.2 on 2024-11-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_spotifywrapped_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifywrapped",
            name="top_artist_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotifywrapped",
            name="top_track_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
