# Generated by Django 5.1.2 on 2024-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_spotifywrapped_top_artist_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifywrapped",
            name="top_artist_image_url",
        ),
        migrations.RemoveField(
            model_name="spotifywrapped",
            name="top_track_image_url",
        ),
        migrations.AddField(
            model_name="spotifywrapped",
            name="top_artists",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spotifywrapped",
            name="top_tracks",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
