# Generated by Django 5.1.1 on 2024-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_spotifywrapped_top_artist_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrapped',
            name='playlist_url',
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='top_artist_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='top_track_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
