# Generated by Django 5.1.1 on 2024-11-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_spotifywrapped_playlist_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrapped',
            name='matching_artists',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='top_track_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
