# Generated by Django 5.1.1 on 2024-11-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_spotifywrapped_matching_artists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifywrapped',
            old_name='top_track_images',
            new_name='top_tracks_images',
        ),
    ]
