# Generated by Django 5.1.3 on 2024-11-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_top_track_images_spotifywrapped_top_tracks_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrapped',
            name='guess_song_game',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='top_3_artists',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='top_3_tracks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
