# Generated by Django 5.1.3 on 2024-11-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_spotifywrapped_guess_song_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrapped',
            name='top_artist_genres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
