# Generated by Django 5.1.3 on 2024-11-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_spotifywrapped_top_artist_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrapped',
            name='top_artist_genres',
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
