# Generated by Django 5.1.3 on 2024-11-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_spotifywrapped_top_artist_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrapped',
            name='guess_song_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
