# Generated by Django 5.1.3 on 2024-12-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_spotifywrapped_guess_song_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifywrapped',
            name='top_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
