# Generated by Django 5.1.3 on 2024-12-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_spotifywrapped_top_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifywrapped',
            name='top_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='top_track',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
